#!/usr/bin/env python3
"""
Turn any text corpus into a pinned lm-eval perplexity task.

    # from a Hugging Face dataset (streamed, so no full download)
    python scripts/make_ppl_task.py --hf HuggingFaceFW/fineweb-edu \
        --config sample-10BT --split train --field text --n 2000 --name ppl_fineweb_edu

    # from your team's own corpus — jsonl, or a directory of .txt files
    python scripts/make_ppl_task.py --local /data/our_corpus.jsonl --field text \
        --n 2000 --name ppl_internal

    # then
    lm_eval --model hf --model_args pretrained=EleutherAI/pythia-160m \
            --include_path eval_tasks --tasks ppl_fineweb_edu --limit 5

WHY THIS EXISTS
    The datasets people list when they talk about LLM data — FineWeb, C4, Dolma,
    RedPajama, Common Crawl — are PRETRAINING corpora. Raw text, no labels, trillions
    of tokens. You cannot score accuracy on them; there is no right answer.

    But they are exactly what you want for the one eval that MULTIPLE-CHOICE
    BENCHMARKS CANNOT GIVE YOU: how well does the model model language, on a domain
    you care about, measured continuously rather than in 25%-increments of luck.

    That matters most in two situations, and you are in both:

      1. Small models. MMLU sits at chance (25%) until models reach the low billions,
         so it cannot distinguish a 14M model from a 410M one. Bits-per-byte can, and
         cleanly — it is continuous and monotone in capability.
      2. Base models. No instruction tuning means no chat template, no format to
         follow, nothing to parse. Perplexity works regardless.

    And the domain slices are the actual product question: perplexity on code vs legal
    vs medical text tells you what a model is for. No public benchmark will tell you
    that about YOUR data.

WHAT IT WRITES
    eval_tasks/<name>.jsonl   the sampled documents — the PINNED item set
    eval_tasks/<name>.yaml    the lm-eval task definition pointing at that file

    Pinning matters: a perplexity number computed on a fresh random sample each time
    is not comparable to last week's. The JSONL is the eval set; commit it, or at
    least keep it, and record its hash. The script prints one.

METRICS, and which to quote
    word_perplexity   exp(total_nll / n_words). Intuitive, but depends on how you
                      count words.
    byte_perplexity   per byte. Tokenizer-independent.
    bits_per_byte     log2(byte_perplexity). THE one to use when comparing models
                      with different tokenizers, which is most cross-family
                      comparisons. Lower is better. Report this.

    Plain token-level perplexity is deliberately not here: it is per-token, so two
    models with different tokenizers produce numbers on different scales and
    comparing them is meaningless.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import sys
import unicodedata
from pathlib import Path

YAML_TEMPLATE = """# Generated by scripts/make_ppl_task.py — do not hand-edit; regenerate instead.
#
# Rolling-loglikelihood perplexity over a pinned document sample.
# Item set: {jsonl}  ({n} docs, sha256 {digest})
# Source:   {source}
task: {name}
dataset_path: json
dataset_kwargs:
  data_files: {jsonl_abs}
output_type: loglikelihood_rolling
training_split: null
validation_split: null
test_split: train
doc_to_text: ""
doc_to_target: "{{{{text}}}}"
should_decontaminate: false
metric_list:
  - metric: word_perplexity
    aggregation: weighted_perplexity
    higher_is_better: false
  - metric: byte_perplexity
    aggregation: weighted_perplexity
    higher_is_better: false
  - metric: bits_per_byte
    aggregation: bits_per_byte
    higher_is_better: false
metadata:
  version: 1.0
"""


def normalise(text: str) -> str:
    """Same normalisation for every corpus, so the comparison is about the text and
    not about whose exporter used which unicode form."""
    text = unicodedata.normalize("NFKC", text)
    return "".join(ch for ch in text if ch in "\n\t" or unicodedata.category(ch)[0] != "C").strip()


def iter_local(path: Path, field: str):
    if path.is_dir():
        for f in sorted(path.rglob("*.txt")):
            yield f.read_text(encoding="utf-8", errors="replace")
        return
    if path.suffix in (".jsonl", ".ndjson"):
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if field in row and isinstance(row[field], str):
                    yield row[field]
        return
    yield path.read_text(encoding="utf-8", errors="replace")


def iter_hf(name: str, config: str | None, split: str, field: str, budget: int):
    try:
        from datasets import load_dataset
    except ImportError:
        sys.exit("pip install datasets")
    # streaming=True so a petabyte-scale corpus costs you only the rows you read.
    ds = load_dataset(name, config, split=split, streaming=True)
    seen = 0
    for row in ds:
        if field not in row:
            sys.exit(f"field {field!r} not in row; available: {sorted(row)[:12]}")
        if isinstance(row[field], str):
            yield row[field]
            seen += 1
            # Read a multiple of what we need, then subsample, so the sample is not
            # just "the first N documents in shard 0".
            if seen >= budget:
                return


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--hf", help="Hugging Face dataset id, e.g. HuggingFaceFW/fineweb-edu")
    src.add_argument("--local", type=Path, help=".jsonl / .txt file, or a directory of .txt")
    ap.add_argument("--config", help="HF dataset config, e.g. sample-10BT")
    ap.add_argument("--split", default="train")
    ap.add_argument("--field", default="text", help="which column holds the text")
    ap.add_argument("--n", type=int, default=2000, help="documents to keep")
    ap.add_argument("--name", required=True, help="task name, e.g. ppl_fineweb_edu")
    ap.add_argument("--min-chars", type=int, default=200,
                    help="drop very short documents; they make perplexity noisy")
    ap.add_argument("--max-chars", type=int, default=20000,
                    help="truncate very long ones so a few outliers don't dominate")
    ap.add_argument("--out-dir", type=Path, default=Path("eval_tasks"))
    ap.add_argument("--seed", type=int, default=1234)
    args = ap.parse_args()

    if not args.name.replace("_", "").isalnum():
        sys.exit("--name should be alphanumeric with underscores")

    source = args.hf or str(args.local)
    if args.hf:
        stream = iter_hf(args.hf, args.config, args.split, args.field, args.n * 5)
        if args.config:
            source += f" ({args.config}, {args.split})"
    else:
        if not args.local.exists():
            sys.exit(f"{args.local} does not exist")
        stream = iter_local(args.local, args.field)

    pool = []
    for text in stream:
        text = normalise(text)
        if len(text) < args.min_chars:
            continue
        pool.append(text[:args.max_chars])

    if not pool:
        sys.exit(f"no documents survived filtering (min_chars={args.min_chars})")

    rng = random.Random(args.seed)
    docs = pool if len(pool) <= args.n else rng.sample(pool, args.n)
    docs.sort()   # deterministic file order regardless of stream order

    args.out_dir.mkdir(parents=True, exist_ok=True)
    jsonl = args.out_dir / f"{args.name}.jsonl"
    with open(jsonl, "w", encoding="utf-8") as fh:
        for d in docs:
            fh.write(json.dumps({"text": d}, ensure_ascii=False) + "\n")

    digest = hashlib.sha256(jsonl.read_bytes()).hexdigest()[:16]
    yaml_path = args.out_dir / f"{args.name}.yaml"
    yaml_path.write_text(YAML_TEMPLATE.format(
        name=args.name, jsonl=jsonl, jsonl_abs=str(jsonl.resolve()),
        n=len(docs), digest=digest, source=source), encoding="utf-8")

    total_bytes = sum(len(d.encode()) for d in docs)
    print(f"wrote {jsonl}  ({len(docs)} docs, {total_bytes / 1e6:.2f} MB of text)")
    print(f"wrote {yaml_path}")
    print(f"item set sha256: {digest}   <- record this; it identifies the eval set")
    print(f"\nverify it registers, cheaply:")
    print(f"  lm_eval --model hf --model_args pretrained=EleutherAI/pythia-160m \\")
    print(f"      --include_path {args.out_dir} --tasks {args.name} --limit 5 --device cuda:0")
    return 0


if __name__ == "__main__":
    # os._exit, not SystemExit: the HF download stack leaves native background
    # threads that can crash CPython during normal interpreter teardown
    # ("Fatal Python error: PyGILState_Release ... no thread-state", core dump) —
    # AFTER every file is written and every message printed. All output paths in
    # this script write-and-close before returning, so skipping finalization
    # loses nothing and turns a scary abort into a clean exit 0.
    try:
        rc = main()
    except SystemExit as e:
        if isinstance(e.code, str):
            print(e.code, file=sys.stderr)
            rc = 1
        else:
            rc = e.code or 0
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(rc if isinstance(rc, int) else 0)
